### ISSUE TITLE
Feature req: Please integrate apipie.ai

### ISSUE THREAD

**Issue by EncryptShawn** [BertKiv/openrouterai-proxy#1]
Instead of integrating, together, openrouter, eden, etc? Why not just integrate APIpie to access them all from one place and plus it also provides:

-The most affordable, reliable and fastest AI available
-One API to access ~500 Models and growing
-Language, embedding, voice, image, vision and more
-Global AI load balancing, route queries based on price or latency
-Redundancy for major models providing the greatest up time possible
-Global reporting of AI availability, pricing and performance

**Comment by BertKiv** [comment]
From README.md:
"This Python FastAPI application acts as a proxy server for [openrouter.ai](https://openrouter.ai/), facilitating the forwarding of incoming HTTP requests to a specified API URL and managing the responses. Notably, it incorporates a feature enabling the automatic waiting in response to a 429 error, effectively bypassing rate limits and enabling the utilization of free-of-charge models for programming and testing purposes without incurring any expenses."

The key phrase is: **utilizing free-of-charge models for programming and testing purposes without incurring any expenses.**
